import 'dart:math';
import 'package:flutter/material.dart';
import 'package:textformfield_example/services/predict.dart';


class Second_screen extends StatelessWidget {
  var _answers = PredictService.getAnswers();


  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('App499 เจษฎาทำได้ !!!!'),
      ),
      body:  ListView.builder(
          itemCount: _answers.length,
          itemBuilder: (context, index) {
        return Text(_answers[index]);
      })
    );
  }
}


// class Second_screen extends StatelessWidget {
//   @override
//   Widget build(BuildContext context) {
//     return Scaffold(
//       appBar: AppBar(
//         title: Text("Result"),
//       ),
//     );
//   }
// }

/*void main() {
  var arr = [
    "Nike Pegasus",
    "New Balance Fresh Foam 1080",
    "Altra escalante",
    "Nike Pegasus Turbo",
    "Adidas Ultra Boost",
    "Adidas duramo",
    "Adidas Ultra Boost",
    "Skechers GoRun",
    "Adidas Ultra Boost 20",
    "Nike free",
    "Nike react infinity run",
    "Adidas Pure boost",
    "Adidas pure boost",
    "Nike Renew Arena",
    "Kismet",
    "Adidas adizero boston 8",
    "Nike react infinity run",
    "Asics Evoride",
    "Adidas SL20",
    "Adidas Duramo 9",
    "Nike Air Max 97",
    "Nike Zoom",
    "Ultraboost",
    "NIKE ROSHE RUN FLYKNIT",
    "Fresh Foam Cruz v2 Nubuck",
    "Fresh Foam Cruz v2 Nubuck",
    "Saucony Type a8",
    "Air max",
    "Nike joyride dual run",
    "Nike roshe run",
    "Adidas Response SR",
    "Adidas pure boost",
    "Hoka carbon X",
    "Hoka carbon X",
    "Hoka Clayton",
    "Hoka rincon 2",
    "Asics Gel nimbus",
    "Adidas ultra boost",
    "Air Zoom Pegasus",
    "Duramo SL",
    "Adidas 20-20 FX",
    "Altra torin",
    "Hoka Rincon",
    "Asics Glidelide",
    "Nike Vaporfly Next%",
    "Nike epic react",
    "Nike Vaporfly Next%",
    "Hoka Clifton",
    "Adidas Adizero prime X",
    "Pan predator",
    "Xtep 160x",
    "Nike vaporfly next% 2",
    "Hoka carbon X",
    "Nike Vaporfly Next%",
    "nike vaporfly next%",
    "new balance fuelcell",
    "Hoka cilfton 7",
    "Saucony Endorphin speed",
    "Hoka carbon X",
    "Pan Predator",
    "Hoka Rocket X",
    "Asics Glideride",
    "New Balance 860",
    "Altra Torin",
    "Hoka Carbon X 2",
    "Hoka carbon X",
    "Mizuno wave rider",
    "Hoka clifton 6",
    "Nike Tempo next%",
    "Nike Pegasus",
    "Asics Novablast",
    "Asics Metaracer",
    "Reebok Floatride Energy",
    "Nike Vaporfly Next%",
    "nike zoom fly flyknit",
    "Adidas ultra boost",
    "Nike Zoom Fly 3",
    "Altra Torin ",
    "New balance fresh foam 1080",
    "Altra Escalanrte",
    "Hoka Arahi4",
    "Saucony Endorphin shift",
    "New Balance Fuelcell Rebel v2",
    "Hoka clifton 6",
    "Hoka Carbon X",
    "Nike zoom fly 3",
    "adidas adizero adios",
    "Saucony Kinvara",
    "Nike Zoom fly 3",
    "Hoka Carbon X 2",
    "Asics Novablast",
    "New Balance rabel",
    "VING 100K",
    "Adidas adizero adios pro",
    "Adios Adizero pro",
    "Hoka rocket X",
    "Hoka Mach 4",
    "Asics Noosa Tri13",
    "Saucony Kinvara11",
    "Saucony Endorphin Pro",
    "Saucony endorphin speed",
    "Adidas Pure Boost",
    "Adidas Adizero boston 9",
    "Hoka Clifton 7",
    "Mizuno wave neo",
    "Adidas adizero adios pro",
    "New Balance Rebel v1",
    "Adidas adizero adios pro",
    "Sauconyn Endrofin speed",
    "Saucony endorphin pro",
    "Hoka rocket x",
    "Saucony Freedom iso",
    "nike zoomfly flyknit",
    "Altra Rivera",
    "Asics Metaracer",
    "Adidas Ultra boost",
    "pan predator",
    "Nike react Infinity Run",
    "Saucony freedom iso",
    "Pan Predator",
    "Mizuno  Wave inspine",
    "Brooks Grycerin",
    "Altra Torin",
    "altra provision",
    "Altra Escalente",
    "Wave rider neo",
    "Saucony Endorphin Speed",
    "Saucony Endorphin pro",
    "Altra torin",
    "Saucony Endorphin Shift",
    "Nike Alphafly next%",
    "qiaodan q-kungfu pro",
    "Hoka clifton7",
    "Adidas sl20.2",
    "Nike zoom fly 3",
    "HOKA CARBON X2",
    "Asics Kayano",
    "Saucony Liberty iso",
    "Asics glideride",
    "UA Flow Velociti",
    "Saucony Triumph",
    "Asics metaracer",
    "Salming enRoute",
    "Altra Rivera",
    "Adidas SL20",
    "Nike Pagasus",
    "HOKA CARBON X2",
    "New balance zante",
    "Hoka clifton 7",
    "asics glideride",
    "New Balance 1080",
    "Hoka Carbon X",
    "Saucony endrophin pro",
    "ASICS KAYANO",
    "Hoka rincon",
    "Nike Zoom fly",
    "Nike Invincible run",
    "Nike tempo next%",
    "Hoka Carbon X",
    "Hoka carbon X 2",
    "Ascis Novablast",
    "New Balance fuelcell rebel",
    "vibram finvefingers v-run",
    "Asics CUMULUS MK22",
    "Nike Invincible run",
    "Saucony Endorphin speed",
    "Nike Vaporfly Next%",
    "Hoka carbon x",
    "Hoka Arahi 5",
    "Nike Invincible run",
    "New Balance Fuelcell Rebel V2",
    "gorun7+",
    "Nike Vaporfly 4%",
    "Pan Predator",
    "Reebok Forever Floatride",
    "New Balance fuelcell Prism",
    "HOKA Carbon X SPE",
    "Adidas Adizero Adios Pro",
    "Pan predator",
    "Hoka clifton 7",
    "Asics Novablast",
    "Altra torin",
    "Asics Novablast",
    "Asics endorphin speed",
    "Asics Novablast",
    "Nike Pegasus turbo 2",
    "Asics Kayano",
    "UA Machina",
    "New Balance 880",
    "Asics Glideride",
    "Saucony Endorphin pro",
    "Altra Paradigm",
    "Brooks Ghost 13",
    "Nike Vaporfly 4%",
    "Saucony Endorphin Pro",
    "Adidas SL20",
    "Asics glideride",
    "Brooks Glycelin 17",
    "Hoka mach 3",
    "Hoka clifton 7",
    "Adidas adizero adios 5",
    "Nike vaporfly next%",
    "Saucony Freedom iso 2",
    "Nike vaporfly next%",
    "Asics novablast",
    "skechers gorun 7+",
    "Nike vaporfly next%",
    "Asics novablast",
    "skechers gorun 7+",
    "Nike vaporfly next%",
    "Adidas Boston 8",
    "Under Armour HOVR Phantom 2",
    "Nike vaporfly next%",
    "Nike React Miler",
    "Hoka​ carbon​ ​xClass",
    "Nike Pegasus",
    "New Balance Fresh Foam 1080",
    "Altra escalante",
    "Nike Pegasus Turbo",
    "Adidas Ultra Boost",
    "Adidas duramo",
    "Adidas Ultra Boost",
    "Skechers GoRun",
    "Adidas Ultra Boost 20",
    "Nike free",
    "Nike react infinity run",
    "Adidas Pure boost",
    "Adidas pure boost",
    "Nike Renew Arena",
    "Adidas adizero boston 8",
    "Nike react infinity run",
    "Asics Evoride",
    "Adidas SL20",
    "Adidas Duramo 9",
    "Nike Air Max 97",
    "Nike Zoom",
    "Ultraboost",
    "NIKE ROSHE RUN FLYKNIT",
    "Fresh Foam Cruz v2 Nubuck",
    "Saucony Type a8",
    "Air max",
    "Nike joyride dual run",
    "Adidas Response SR",
    "Hoka carbon X",
    "Hoka Clayton",
    "Hoka rincon 2",
    "Asics Gel nimbus",
    "Air Zoom Pegasus",
    "Duramo SL",
    "Adidas 20-20 FX",
    "Altra torin",
    "Hoka Rincon",
    "Asics Glidelide",
    "Nike Vaporfly Next%",
    "Nike epic react",
    "Nike Vaporfly Next%",
    "Hoka Clifton",
    "Adidas Adizero prime X",
    "Pan predator",
    "Xtep 160x",
    "Nike vaporfly next% 2",
    "Hoka carbon X",
    "Nike Vaporfly Next%",
    "nike vaporfly next%",
    "new balance fuelcell",
    "Hoka cilfton 7",
    "Saucony Endorphin speed",
    "Hoka carbon X",
    "Pan Predator",
    "Hoka Rocket X",
    "Asics Glideride",
    "New Balance 860",
    "Altra Torin ",
    "Hoka Carbon X 2",
    "Hoka carbon X",
    "Mizuno wave rider",
    "Hoka clifton 6",
    "Nike Tempo next%",
    "Nike Pegasus",
    "Asics Novablast",
    "Asics Metaracer",
    "Reebok Floatride Energy",
    "Nike Vaporfly Next%",
    "nike zoom fly flyknit",
    "Adidas ultra boost",
    "Nike Zoom Fly 3",
    "Altra Torin",
    "New balance fresh foam 1080",
    "Altra Escalanrte",
    "Hoka Arahi4",
    "Saucony Endorphin shift",
    "New Balance Fuelcell Rebel v2",
    "Hoka clifton 6",
    "Hoka Carbon X",
    "Nike zoom fly 3",
    "adidas adizero adios",
    "Saucony Kinvara",
    "Nike Zoom fly 3",
    "Hoka Carbon X 2",
    "Asics Novablast",
    "New Balance rabel",
    "VING 100K,"
        "Adidas adizero adios pro",
    "Adios Adizero pro",
    "Hoka rocket X",
    "Hoka Mach 4",
    "Asics Noosa Tri13",
    "Saucony Kinvara11",
    "Saucony Endorphin Pro",
    "Saucony endorphin speed",
    "Adidas Pure Boost",
    "Adidas Adizero boston 9",
    "Hoka Clifton 7",
    "Mizuno wave neo",
    "Adidas adizero adios pro",
    "New Balance Rebel v1",
    "Adidas adizero adios pro",
    "Sauconyn Endrofin speed",
    "Saucony endorphin pro",
    "Hoka rocket x",
    "Saucony Freedom iso",
    "nike zoomfly flyknit",
    "Altra Rivera",
    "Asics Metaracer",
    "Adidas Ultra boost",
    "pan predator",
    "Nike react Infinity Run",
    "Saucony freedom iso",
    "Pan Predator",
    "Mizuno  Wave inspine",
    "Brooks Grycerin",
    "Altra Torin",
    "altra provision",
    "Altra Escalente",
    "Wave rider neo",
    "Saucony Endorphin Speed",
    "Saucony Endorphin pro",
    "Altra torin",
    "Saucony Endorphin Shift",
    "Nike Alphafly next%",
    "qiaodan q-kungfu pro",
    "Hoka clifton7",
    "Adidas sl20.2",
    "Nike zoom fly 3",
    "HOKA CARBON X2",
    "Asics Kayano",
    "Saucony Liberty iso",
    "Asics glideride",
    "UA Flow Velociti",
    "Saucony Triumph",
    "Asics metaracer",
    "Salming enRoute",
    "Altra Rivera",
    "Adidas SL20",
    "Nike Pagasus",
    "HOKA CARBON X2",
    "New balance zante",
    "Hoka clifton 7",
    "asics glideride",
    "New Balance 1080",
    "Hoka Carbon X",
    "Saucony endrophin pro",
    "ASICS KAYANO",
    "Hoka rincon",
    "Nike Zoom fly",
    "Nike Invincible run",
    "Nike tempo next%",
    "Hoka Carbon X",
    "Hoka carbon X 2",
    "Ascis Novablast",
    "New Balance fuelcell rebel",
    "vibram finvefingers v-run",
    "Asics CUMULUS MK22",
    "Nike Invincible run",
    "Saucony Endorphin speed",
    "Nike Vaporfly Next%",
    "Hoka carbon x",
    "Hoka Arahi 5",
    "Nike Invincible run",
    "New Balance Fuelcell Rebel V2",
    "gorun7+",
    "Nike Vaporfly 4%",
    "Pan Predator ",
    "Reebok Forever Floatride",
    "New Balance fuelcell Prism",
    "HOKA Carbon X SPE",
    "Adidas Adizero Adios Pro",
    "Pan predator ",
    "Hoka clifton 7",
    "Asics Novablast",
    "Altra torin",
    "Asics Novablast",
    "Asics endorphin speed",
    "Asics Novablast",
    "Nike Pegasus turbo 2",
    "Asics Kayano",
    "UA Machina",
    "New Balance 880",
    "Asics Glideride",
    "Saucony Endorphin pro",
    "Altra Paradigm",
    "Brooks Ghost 13",
    "Nike Vaporfly 4%",
    "Saucony Endorphin Pro",
    "Adidas SL20",
    "Asics glideride ",
    "Brooks Glycelin 17",
    "Hoka mach 3",
    "Hoka clifton 7",
    "Adidas adizero adios 5",
    "Nike vaporfly next%",
    "Saucony Freedom iso 2",
    "Nike vaporfly next%",
    "Asics novablast",
    "skechers gorun 7+",
    "Nike vaporfly next%",
    "Asics novablast",
    "skechers gorun 7+",
    "Nike vaporfly next%",
    "Adidas Boston 8",
    "Under Armour HOVR Phantom 2",
    "Nike vaporfly next%",
    "Nike React Miler",
    "Hoka carbon x"
  ];
  var random = new Random();

  List<int> rands = [];

  while (rands.length < 3) {
    int randNo = random.nextInt(arr.length);
    if (!rands.contains(randNo)) {
      rands.add(randNo);
    }
  }

  for (int no in rands) {
    print(arr[no]);
  }
}*/
